#!/bin/bash 

# Compilation of wave boundary conditions / relaxation zone
( cd src; ./Allwmake )

# Compilation of solvers
apps="applications"

# The "-0" is for zero-padding the version number, to accept differences between e.g. 2.1 and 2.1.1
if [ `uname` == "Darwin" ]
then
    version=`echo $WM_PROJECT_VERSION"-0" | sed -e 's/\.x/-0/' -e 's/\./\'$'\n/g' -e 's/-/\'$'\n/g' | grep "[0-9]" | head -3 | tr -d '\n'`
else
    version=`echo $WM_PROJECT_VERSION"-0" | sed -e 's/\.x/-0/' -e 's/\./\n/g' -e 's/-/\n/g' | grep "[0-9]" | head -3 | tr -d '\n'`
fi
export WM_PROJECT_VERSION_NUMBER=$version

# Is the compilation based on the OpenFoam-extend branch. Included to readify the source code
# for a future release, where this option is needed
extBranch=`echo $WM_PROJECT_VERSION | grep 'dev\|ext'`

if [ -z $extBranch ]
then
    extBranch=0
else
    extBranch=1
fi

export extBranch

# Apply the correct Make folder
if [ "$extBranch" -eq "1" ]
then
    rm -f $PWD/$apps/solvers/solvers$version/waveFoam/Make/options
    ln -s -f $PWD/$apps/solvers/solvers$version/waveFoam/Make/options.ext \
             $PWD/$apps/solvers/solvers$version/waveFoam/Make/options
else
    if [ -f $PWD/$apps/solvers/solvers$version/waveFoam/Make/options.reg ]
    then
        rm -f $PWD/$apps/solvers/solvers$version/waveFoam/Make/options
        ln -s -f $PWD/$apps/solvers/solvers$version/waveFoam/Make/options.reg \
                 $PWD/$apps/solvers/solvers$version/waveFoam/Make/options
    fi
fi

( cd $apps/solvers/solvers$version && wmake all )

# Compilation of utilities
rm -f $PWD/applications/utilities/postProcessing/surfaceElevation/Make/options

if [ "$WM_PROJECT_VERSION_NUMBER" -lt "220" ]
then
    ln -s -f $PWD/applications/utilities/postProcessing/surfaceElevation/Make/options.210 \
             $PWD/applications/utilities/postProcessing/surfaceElevation/Make/options
else
    ln -s -f $PWD/applications/utilities/postProcessing/surfaceElevation/Make/options.220 \
             $PWD/applications/utilities/postProcessing/surfaceElevation/Make/options
fi

( cd $apps/utilities && wmake all )
