#!/bin/bash 

# Remove option "-llduSolvers" from non-extended versions of OF

arg=`echo $WM_PROJECT_VERSION | grep 'dev\|ext'`

if [ -z "$arg" ] 
then

    list=`find ./ -name "options" | grep -v $WM_OPTIONS`
    
    for i in $list
    do
        dir=`dirname $i`

        cd $dir

        argInner=`grep -v "\-llduSolvers" options`

        if [ -z "$argInner" ]
        then 
            grep -v "\-llduSolvers" options > options.temp
            mv options.temp options
        fi

        cd $OLDPWD
    done
fi

# Compilation of wave boundary conditions / relaxation zone

( cd src; ./Allwmake )

# Compilation of solvers
# Here there is a very clear destingtion between version 1.5 and 1.6+. Hence solvers more recent than
# 1.5 are compile in the same directory

apps="applications"

version=`echo $WM_PROJECT_VERSION | sed -e 's/\./\n/g' -e 's/-/\n/' | grep "[0-9]" | head -2 | tr -d '\n'`
export WM_PROJECT_VERSION_NUMBER=$version

( cd $apps/solvers/solvers$version && wmake all )

# Compilation of utilities

( cd $apps/utilities && wmake all )

