#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

sh ../../../bin/prepareCase.sh

# Set application name
application="waveFoam"

runApplication blockMesh
runApplication setWaveField
runApplication $application
