#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

sh ../../../bin/prepareCase.sh

# Set application name
application="waveFoam"

# Create mesh
runApplication blockMesh

# Create internal wall
runApplication faceSet
runApplication setsToZones -noFlipMap
runApplication createBaffles f0 internalWall -overwrite

# Set wave parameters
cp constant/waveProperties constant/waveProperties.input

runApplication setWaveParameters

# Set wave field
runApplication setWaveField

# Run application
runApplication $application


