#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

exec="../../../bin/prepareCase.sh"

if [ -x "$exec" ]
then
    . $exec
else
    echo "The file $WAVES_DIR/bin/prepareCase.sh is not executable."
    echo "Make the file executable before continuing."
    echo
    echo "Exiting tutorial case."
    exit 1
fi

# Set application name
application="waveFoam"

# Create mesh
runApplication blockMesh

# Create internal wall
runApplication faceSet
runApplication setsToZones -noFlipMap
runApplication createBaffles f0 internalWall -overwrite

# Set wave parameters
runApplication setWaveParameters

# Set wave field
runApplication setWaveField

# Run application
runApplication $application


